### PR TITLE
Fixed a typo

### PR DESCRIPTION
**Pull request by HammyHavoc**
:- )

Whilst I'm here; am I right in thinking that this won't work with a USB-connected printer? I.e. it needs to already be shared on the network through another machine?

### CODE REVIEW

**Comment by DrPsychick** [comment]
Thanks!

Yes it should work with an USB printer attached to the where the container runs, and I guess you have to explicitly give it access to the USB device. I haven't tried that though.

**Comment by sunmeplz** [comment]
Hi there!
I have tired to run local usb printer with your image and had no luck because the usb backend wasn't attached, that was fixed by adding symlink ln -s /usr/lib/cups/backend-available/usb /usr/lib/cups/backend/usb

**Comment by DrPsychick** [comment]
Hi @HammyHavoc ,

I just pushed an update to the `dev` branch which keeps the `/usr/lib/cups/backend/usb`. Unfortunately travis build isn't working currently... I'll try to push an update to docker hub manually.

**Comment by DrPsychick** [comment]
@HammyHavoc 
So, I just pushed a new image to `drpsychick/airprint-bridge:dev`, try that one with the `--device` flag - in the end it was my fault, as I deleted the local backends `usb, serial, parallel` in the original Dockerfile.

Thanks for pointing that out!

Are you willing to help me add a "Howto use airpint-bridge with a USB printer" to this repo?
I would just need the actual commands you used to get it up and running and maybe a few bullet points about the issues you ran into. If you have any "visible" documentation on how that works, that would be awesome (screenshots/photos, if they would help someon else to replicate your setup).

**Comment by DrPsychick** [comment]
-> I'll close and merge this. For further talk (also the documentation of USB printer attached), let's create a new issue.

**Pull request merged**
