### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by netcookies**
Bring back usb support ( For Synology).

### CODE REVIEW

**Comment by DrPsychick** [comment]
If you add saned (which is awesome!), please make it optional through ENV, default to off (to be backwards compatible).

If you wanna chat, send me an email and I'll invite you to slack: drpsychick/drsick.de

**Comment by netcookies** [comment]
ok, still being working on add saned. Do u have telegram?

**Comment by DrPsychick** [comment]
Yes, I poked you on telegram. Let me know when you're done for merging the PR.

**Comment by DrPsychick** [comment]
Hi @netcookies , did yo make progress?

**Comment by netcookies** [comment]
Yeah. I am very busy recently during lunar year, and will continue to work ASAP,

**Comment by DrPsychick** [comment]
@netcookies : I'll close this as the newest image contains many of your suggestions. Thank you very much for participating!

Please do share your results with `saned` when you're ready, I'll happily include it in the image.

**Pull request closed without merging**
